# Generated by Django 3.2 on 2022-09-15 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0004_likecomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.comment')),
            ],
        ),
        migrations.CreateModel(
            name='ReactionTweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ReactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('reaction_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='liketweet',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='liketweet',
            name='tweet',
        ),
        migrations.RemoveField(
            model_name='liketweet',
            name='user',
        ),
        migrations.DeleteModel(
            name='LikeComment',
        ),
        migrations.DeleteModel(
            name='LikeTweet',
        ),
        migrations.AddField(
            model_name='reactiontweet',
            name='reaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.reactiontype'),
        ),
        migrations.AddField(
            model_name='reactiontweet',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.tweet'),
        ),
        migrations.AddField(
            model_name='reactiontweet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reactioncomment',
            name='reaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.reactiontype'),
        ),
        migrations.AddField(
            model_name='reactioncomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='reactiontweet',
            unique_together={('user', 'tweet')},
        ),
        migrations.AlterUniqueTogether(
            name='reactioncomment',
            unique_together={('user', 'comment')},
        ),
    ]
